
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Character.isDigit;
import static java.lang.Character.isLetter;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

public class FormRegisto extends javax.swing.JFrame {

    /**
     * Creates new form FormRegisto
     */
    public FormRegisto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ctxpass = new javax.swing.JPasswordField();
        ctxREpass = new javax.swing.JPasswordField();
        ctxNome = new javax.swing.JTextField();
        ctxemail = new javax.swing.JTextField();
        ctxmorada = new javax.swing.JTextField();
        ctxtelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ctxvalidar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ctxNIF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ctxlogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NIF:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Morada:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Reescreva password:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password:");

        ctxpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxpassActionPerformed(evt);
            }
        });

        ctxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxNomeActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setText("Registro de Utilizador");

        ctxvalidar.setBackground(new java.awt.Color(51, 255, 51));
        ctxvalidar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ctxvalidar.setText("REGISTRAR UTILIZADOR");
        ctxvalidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxvalidarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Número telefônico:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Login");

        ctxlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ctxNome, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(ctxemail)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ctxvalidar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctxREpass))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addComponent(ctxpass, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctxmorada)
                            .addComponent(ctxNIF)
                            .addComponent(ctxlogin)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctxtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(ctxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctxemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxmorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxREpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ctxvalidar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login log = new Login();
        try {
            this.finalize();
        } catch (Throwable ex) {
            
        }
        log.setVisible(true);      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ctxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxNomeActionPerformed

    private void ctxpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxpassActionPerformed
        private void mensagemErro(String erro){
            JOptionPane.showMessageDialog(null, erro, "Erro Validação", JOptionPane.ERROR_MESSAGE);
        }
    private void ctxvalidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxvalidarActionPerformed
    String nome = ctxNome.getText();
    String email = ctxemail.getText();
    String morada = ctxmorada.getText();
    String telefone = ctxNIF.getText();
    String NIF = ctxtelefone.getText();
    String password = ctxpass.getText();
    String REpass = ctxREpass.getText();
    String loginN = ctxlogin.getText();
    System.out.println("Password"+password);
    System.out.println("REpass"+REpass);
    /*mensagemErro("teste");*/
        //email tem de ter 1 @ e 1. após o @
        //morada tem de ter>5 caracteres
        //telefone 9 caracteres que sejam digito
        //nif 9 caracteres que sejam digito
        //pass e rePass tem de ser iguais
        //pass 8 ou + caracteres, 1ou+ minusculas
        //1 ou+ algarismos, 1 ou+ maiusculas,
        //1 ou+ caracteres especiais
    if(email.equals("") || nome.equals("") || morada.equals("") ||
            telefone.equals("") || NIF.equals("") || REpass.equals("") || password.equals("")){
      mensagemErro("Preencha todos os campos!"); 
    }else{
       if (!ValidaCampoNome(nome)){
          mensagemErro("O campo nome tem " + " de ter 2 caracteres alfabéticos");
            }
        if (!ValidaCampoEmail(email)){
            mensagemErro("O campo e-mail tem que conter @.");
        }
        if (!ValidaCampoNumerico(telefone)){
          mensagemErro("O campo telefone tem de conter 9 digítos numéricos"); 
            }
        if (!ValidaCampoNumerico(NIF)){
          mensagemErro("O campo NIF tem de conter 9 digítos numéricos");
            }
        if (!ValidaCampoMorada(morada)){
          mensagemErro("O campo morada tem de conter mais 5 caracteres");
            }
        if (!ValidaCampoPassword(password)){
          mensagemErro("O campo password tem de conter 8 caracteres");
            }
        if (!password.equals(REpass)){
            mensagemErro("As passawords não coincidem");                                                                                                                                                                                                                                                                                                                                                                                                                                     
        }
        //»»»»»»»»»»»»»»»»»»»»»»LOGIN«««««««««««««««««««««««««««««
        
          
        File ficheiro = new File (nome+".txt");
        if(!ficheiro.exists()){
           try{
               ficheiro.createNewFile();
               FileWriter fw = new FileWriter(ficheiro);
                BufferedWriter bw = new BufferedWriter (fw);
                bw.write(password);
                bw.newLine();
                bw.write(REpass);
                bw.newLine();
                bw.write(nome);
                bw.newLine();
                bw.write(email);
                bw.newLine();
                bw.write(morada);
                bw.newLine();
                bw.write(NIF);
                bw.newLine();
                bw.write(telefone);
                bw.newLine();
                bw.close();
                fw.close();
           } catch (IOException ex){
                ex.printStackTrace();
            }
         
 }
           try {
               LIgaBD.registaUtilizador(nome, email, morada, Integer.parseInt(telefone), Integer.parseInt(NIF), loginN, password);
           } catch (SQLException ex) {
               Logger.getLogger(FormRegisto.class.getName()).log(Level.SEVERE, null, ex);
           }
            
        
        
            
    






}
    }//GEN-LAST:event_ctxvalidarActionPerformed
    private void ctxloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxloginActionPerformed
 
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegisto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ctxNIF;
    private javax.swing.JTextField ctxNome;
    private javax.swing.JPasswordField ctxREpass;
    private javax.swing.JTextField ctxemail;
    private javax.swing.JTextField ctxlogin;
    private javax.swing.JTextField ctxmorada;
    private javax.swing.JPasswordField ctxpass;
    private javax.swing.JTextField ctxtelefone;
    private javax.swing.JButton ctxvalidar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private boolean ValidaCampoNumerico(String valor) {
        int x, contador=0, t=valor.length();
        char c;
        if(t!=9)
            return false;
        else{
            for(x=0;x<t;x++){
                c = valor.charAt(x);
                if(isDigit(c))
                    contador++;
            }
            if(t!=contador)
                return false;
        }
        return true;    
    }

    private boolean ValidaCampoNome(String nome) {
        int x, contador = 0, t= nome.length();
        char c;
        if (t <2)
            return false;
        else{
            for (x = 0; x<t; x++){
                c = nome.charAt(x);
                if (isLetter(c))
                    contador++;
            }
            if (t!=contador)
                return false;
        }
        return true;
    }

    private boolean ValidaCampoMorada(String morada) {
        int x, contador = 0, t = morada.length();
        char k;
        if (t<5)
            return false;
        else{
            for (x = 0; x<t; x++){
                k = morada.charAt(x);
                if (isLetter(k))
                    contador++;
            }
            if (t!=contador)
                return false;
        }
        return true;
    }

   private boolean ValidaCampoPassword(String password) {
       int x = 0, p = password.length();
        int mai = 0;
        int min = 0;
        int num = 0;
        int sc = 0;
        if (p < 8)
            return false;
        for (x = 0; x < p; x++){
            char c = password.charAt(x);
            if (c == ' ')
                return false;
            if (Character.isDigit(c)){
                num++;
            }
            if (Character.isUpperCase(c)){
                mai++;
            }
            if (Character.isLowerCase(c)){
                min++;
            }
            if (!isDigit(c) && !isLetter(c))
                sc++;
    
         }
    if (min > 0 && mai> 0 && sc > 0 && num > 0)
        return true;
    else
         return false;
    }

    private boolean ValidaCampoEmail(String email) {
        int c = 0 ,  e = email.length();
        if (email.indexOf("@") >= 1 ) {
        if (email.indexOf(".") >= email.indexOf("@")+2)
        return true;    
       if ((email.indexOf("@")+email.indexOf(".") - email.length()) >= 1 )
         System.out.print("Email aprovado" + (email.length() - (email.indexOf("@")+email.indexOf("."))));
       }
        return false;
    }
 }
  

