import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException; 
import java.io.InputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
public class MenoOpcoes extends javax.swing.JFrame {
    public static Scanner ler = new Scanner (System.in);
    public MenoOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public static String login;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MOSTRAR = new javax.swing.JButton();
        DELETAR = new javax.swing.JButton();
        VISUALIZAR = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        SAIRFORA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MOSTRAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MOSTRAR.setText("Mostrar Utilizadores Registrados");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        DELETAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DELETAR.setText("Eliminar Utilizador");
        DELETAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETARActionPerformed(evt);
            }
        });

        VISUALIZAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VISUALIZAR.setText("Visualizar Dados Utilizador");
        VISUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VISUALIZARActionPerformed(evt);
            }
        });

        EDITAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EDITAR.setText("Editar Dados Utilizador");
        EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARActionPerformed(evt);
            }
        });

        SAIRFORA.setBackground(new java.awt.Color(255, 0, 0));
        SAIRFORA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SAIRFORA.setText("SAIR");
        SAIRFORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRFORAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VISUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DELETAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MOSTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(EDITAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SAIRFORA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DELETAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(VISUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(SAIRFORA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VISUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VISUALIZARActionPerformed
        // TODO add your handling code here: 
        File ficheiro = new File (Login.login+".txt");
        
        if(!ficheiro.exists()){
            System.out.println("Os dados não existem!");
        }else{
            
            try{
                FileReader fr = new FileReader (ficheiro);
                BufferedReader br = new BufferedReader (fr);
                while (br.ready()){
                    String linha = br.readLine ();
                    System.out.println (linha);
                }
                br.close();
                br.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ioe) {
                
            }
        }
    }//GEN-LAST:event_VISUALIZARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
        // TODO add your handling code here:
        File ficheiro = new File("C:\\Users\\TLeite\\Desktop\\login\\SistemasLogin\\SistemasLogin");
        File [] lista = ficheiro.listFiles();
        System.out.println("»»»» Lista de Dados ««««");
        for(int x=0;x<lista.length;x++){
            String valor = " ";
            valor = (lista[x].toString());
            if (valor.endsWith (".txt")){
            System.out.println(lista[x].getName());
            }
        }
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void DELETARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETARActionPerformed
        // TODO add your handling code here:
        //Usar o delete. Deletar o ficheiro
       File ficheiro = new File(Login.login+".txt");
       if(ficheiro.exists()){
            ficheiro.delete();
            System.out.println("O login foi deletado!");
                
       }
    }//GEN-LAST:event_DELETARActionPerformed

    private void SAIRFORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRFORAActionPerformed

         //sair botão
        // TODO add your handling code here:
        Login fr = new Login ();
        this.setVisible(false);
        fr.setVisible(true);  

    }//GEN-LAST:event_SAIRFORAActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
        try {
            EditUtil eu = new EditUtil();
            this.setVisible(false); 
            eu.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenoOpcoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EDITARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenoOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenoOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenoOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenoOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenoOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETAR;
    private javax.swing.JButton EDITAR;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JButton SAIRFORA;
    private javax.swing.JButton VISUALIZAR;
    // End of variables declaration//GEN-END:variables

    
}
